// ---- i18n strings (bn = Bangla, en = English) ----
export const STRINGS = {
  bn: {
    appTitle: "TotalTap",
    wrongCalc: "ভুল হিসাব",
    cash: "নগদ",
    due: "বাকি",
    newNote: "নতুন নোট",
    thisMonth: "এ মাসে",
    dueTooltip: "এই হিসাবটা বাকি হিসেবে জমা হবে",
    tapTooltip: "এই হিসাবটা এই নোটে যোগ করতে ট্যাপ করুন",
    hintDue:
      'এখন "বাকি" মোডে আছেন — নোট বাটনে ট্যাপ করলে এই হিসাবটা বাকি হিসেবে জমা হবে',
    hintNormal: "হিসাব করার পর উপরের নোট বাটনে ট্যাপ করলেই যোগ হয়ে যাবে",
    notesTitle: "আমার নোটগুলো",
    noNotes1: "এখনো কোনো নোট তৈরি হয়নি।",
    noNotes2: 'ক্যালকুলেটর থেকে "নতুন নোট" চাপুন।',
    entriesTotal: (n) => `মোট ${n}টি হিসাব`,
    createNote: "নতুন নোট তৈরি করুন",
    monthTotalLabel: "এই মাসের মোট খরচ",
    duesListTitle: (total) => `বাকির তালিকা — মোট ৳${total}`,
    takenAt: "বাকি নেওয়া হয়েছে:",
    settle: "পরিশোধ করুন",
    settleModalTitle: "কত টাকা পরিশোধ করতে চান?",
    settleModalSubtitle: (total) =>
      `মোট বাকি ৳${total} — পুরোটা অথবা যেকোনো অংশ পরিশোধ করতে পারেন`,
    payFull: (amt) => `পুরো ৳${amt} পরিশোধ`,
    payHalf: (amt) => `অর্ধেক ৳${amt}`,
    remainingDueNote: (amt) => `বাকি ৳${amt} এখনো "বাকির তালিকায়" থেকে যাবে`,
    addToCalculator: "ক্যালকুলেটরে যোগ করুন",
    settlingBanner: "পরিশোধ হচ্ছে — নোটে অ্যাড করলে এগুলো সেটেল্ড হয়ে যাবে",
    removeQueued: "বাদ দিন",
    noEntries: "এখনো কোনো হিসাব যোগ হয়নি।",
    wasDue: "(বাকি ছিল)",
    takenLabel: "বাকি নিয়েছেন:",
    settledLabel: "পরিশোধ:",
    notifTitle: "নোটিফিকেশন",
    noNotif1: "কোনো নতুন নোটিফিকেশন নেই।",
    noNotif2: "কোনো মাস শেষ হলে এখানে হিসাব দেখাবে।",
    monthEnded: (label) => `${label} শেষ হয়েছে`,
    notifSpentLine: (name) => `"${name}" নোটে এ মাসে মোট খরচ হয়েছে`,
    notifFootnote:
      "এই মাসের হিসাব মুছে যায়নি, নোটের ভেতরে আলাদা করে সংরক্ষিত আছে।",
    ok: "ঠিক আছে",
    addNoteTitle: "নতুন নোটের নাম দিন",
    addNotePlaceholder: "যেমনঃ চা-নাস্তা, রিকশা ভাড়া",
    cancel: "বাতিল",
    create: "তৈরি করুন",
    notifAria: "নোটিফিকেশন",
    notesAria: "নোট দেখুন",
    langToggleAria: "ভাষা পরিবর্তন করুন",
    loginWithGoogle: "Google দিয়ে লগইন করুন",
    logout: "লগআউট",
    syncedAs: (email) => `${email} হিসেবে সিঙ্ক হচ্ছে`,
    syncPulling: "আগের হিসাব লোড হচ্ছে…",
    syncError: "সিঙ্ক করতে সমস্যা হয়েছে, আবার চেষ্টা করুন",
    accountHint:
      "লগইন করলে আপনার সব হিসাব আপনার Google অ্যাকাউন্টের সাথে সংরক্ষিত থাকবে — অ্যাপ আনইনস্টল করলে বা নতুন করে ডাউনলোড করলেও লগইন করলেই সব ফিরে পাবেন।",
  },
  en: {
    appTitle: "TotalTap",
    wrongCalc: "Invalid calculation",
    cash: "Cash",
    due: "Due",
    newNote: "New note",
    thisMonth: "This month",
    dueTooltip: "This amount will be logged as due (credit)",
    tapTooltip: "Tap to add this amount to the note",
    hintDue:
      'You\'re in "Due" mode — tapping a note button will log this amount as unpaid credit',
    hintNormal: "After calculating, tap a note button above to log it",
    notesTitle: "My Notes",
    noNotes1: "No notes created yet.",
    noNotes2: 'Tap "New note" from the calculator.',
    entriesTotal: (n) => `${n} entries total`,
    createNote: "Create new note",
    monthTotalLabel: "This month's total spend",
    duesListTitle: (total) => `Outstanding dues — total ৳${total}`,
    takenAt: "Taken on:",
    settle: "Settle",
    settleModalTitle: "How much do you want to pay?",
    settleModalSubtitle: (total) =>
      `Total due ৳${total} — pay all of it or any part now`,
    payFull: (amt) => `Pay full ৳${amt}`,
    payHalf: (amt) => `Half ৳${amt}`,
    remainingDueNote: (amt) => `৳${amt} will remain in the outstanding dues list`,
    addToCalculator: "Add to calculator",
    settlingBanner: "Settling in progress — adding to the note will settle these",
    removeQueued: "Remove",
    noEntries: "No entries logged yet.",
    wasDue: "(was due)",
    takenLabel: "Taken:",
    settledLabel: "Settled:",
    notifTitle: "Notifications",
    noNotif1: "No new notifications.",
    noNotif2: "When a month ends, its summary will show up here.",
    monthEnded: (label) => `${label} has ended`,
    notifSpentLine: (name) => `Total spent in "${name}" this month`,
    notifFootnote:
      "This month's data hasn't been deleted — it's saved inside the note.",
    ok: "OK",
    addNoteTitle: "Name your new note",
    addNotePlaceholder: "e.g. Tea & Snacks, Rickshaw Fare",
    cancel: "Cancel",
    create: "Create",
    notifAria: "Notifications",
    notesAria: "View notes",
    langToggleAria: "Change language",
    loginWithGoogle: "Sign in with Google",
    logout: "Log out",
    syncedAs: (email) => `Synced as ${email}`,
    syncPulling: "Loading your saved data…",
    syncError: "Sync failed, please try again",
    accountHint:
      "Signing in saves all your entries to your Google account — if you uninstall or reinstall the app, signing in again brings everything back.",
  },
};

export const LANG_STORAGE_KEY = "totaltap_lang";
